name: Pylint

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint mysqlclient
    - name: Check for compile errors with pylint
      run: |
        pylint -E $(git ls-files '*.py')
    #- name: Full code analysis with pylint
    #  run: |
    #    pylint $(git ls-files '*.py')
